### ISSUE TITLE
Any way to have this connect via TCP ?

### ISSUE THREAD

**Issue by thespillmonkey** [raudette/meshtastic_discord_bridge#1]
Any way to have this connect via TCP ?

**Comment by raudette** [comment]
Today, it is not possible - it is hardcoded to use the serial port.  But it is just using the Meshtastic library - it would not be hard to tweak.  I’ll take a look.

**Comment by raudette** [comment]
I've added support for TCP.  To enable it, download the latest release and specify the hostname of your device in the MESHTASTIC_HOSTNAME .env variable.  If no hostname is specified, a serial interface is assumed.
