### ISSUE TITLE
$activenodes empty list.

### ISSUE THREAD

**Issue by limes-github** [raudette/meshtastic_discord_bridge#2]
Sometimes using $activenodes returns empty list. Cannot reproduce every time, but restarting the python script solves it. Any ideas?

**Comment by raudette** [comment]
I definitely see this issue - I haven't yet been able to figure it out, I'll post something here when I do.

**Comment by raudette** [comment]
I had a bit of time to play with this today - there seems to be a send limit for Discord of 2000 characters, if the activenode list got too long, it would just stop sending.
I've just committed a change that limits the node list message to 1900 characters (it cuts off everything afterwards).  Probably have to look into sending multiple messages.

Let me know if this solves your issue.

**Comment by limes-github** [comment]
Hey! Thanks for reply!

I git cloned the repo, copied the .env and got this:

`Error: Could not connect object of type 'NoneType' has no len()
Task exception was never retrieved
future: <Task finished name='Task-8' coro=<MyClient.my_background_task() done, defined at /root/meshtastic_discord_bridge/meshtastic_discord_bridge.py:86> exception=SystemExit(1)>
Traceback (most recent call last):
  File "/root/meshtastic_discord_bridge/meshtastic_discord_bridge.py", line 94, in my_background_task
    if len(meshtastic_hostname)>1:
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/client.py", line 869, in run
    asyncio.run(runner())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/meshtastic_discord_bridge/meshtastic_discord_bridge.py", line 102, in my_background_task
    sys.exit(1)
SystemExit: 1`

The "older" one still works.
Just to let you know. Also - it is not a very important issue, take your time :)

> I had a bit of time to play with this today - there seems to be a send limit for Discord of 2000 characters, if the activenode list got too long, it would just stop sending. I've just committed a change that limits the node list message to 1900 characters (it cuts off everything afterwards). Probably have to look into sending multiple messages.
> 
> Let me know if this solves your issue.

**Comment by raudette** [comment]
Oh - I made one more change - I added a variable to the .env file so you can connect via TCP.  If you are using serial, just leave the variable empty.  Add the following to the .env and I think the problem will go away:
MESHTASTIC_HOSTNAME=""

**Comment by limes-github** [comment]
All seems working well!
TCP is much more handy in my case than serial :) Great job - thank you.

> Oh - I made one more change - I added a variable to the .env file so you can connect via TCP. If you are using serial, just leave the variable empty. Add the following to the .env and I think the problem will go away: MESHTASTIC_HOSTNAME=""

**Comment by limes-github** [comment]
Developer solved the issue and added new functionality.

**Comment by raudette** [comment]
I've made a further change to $activenodes - the first solution I limited the node list to 1900 characters, cutting off any nodes beyond the first 1900 characters.  I'm now breaking the nodelist into 1900 character chunks, and sending them over multiple messages.

**Comment by limes-github** [comment]
Definitely I am going to check this out. Thanks once again!
